[package]
name = "mp4_merger"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
mp4-merge = "0.1.10"

[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "mp4_merger"